# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push]

env:
  CI: true
  FORCE_COLOR: '1' # https://github.com/chalk/chalk/issues/203

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install, lint & test
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn tsc --noEmit
